import { DiscoverTVType, MovieReleaseType, type LanguageISO6391 } from '@lorenzopant/tmdb';
import type { Option } from '@/types';

export const DEFAULT_MOVIE_SEARCH = {
  adult: false,
  genres: [] as number[],
  keywords: [] as Option[],
  originalLanguage: undefined,
  ratingMax: 10,
  ratingMin: 0,
  releaseTypes: [] as MovieReleaseType[],
  releasedAfter: undefined,
  releasedBefore: undefined,
  runtimeMax: 300,
  runtimeMin: 0,
  sort: 'popularity',
  sortDir: 'desc',
  studios: [] as Option[],
  voteCountMax: 1000,
  voteCountMin: 0,
  watchProviders: [] as number[],
} as const;

export const DEFAULT_SERIES_SEARCH = {
  adult: false,
  firstAirDateAfter: undefined,
  firstAirDateBefore: undefined,
  genres: [] as number[],
  keywords: [] as Option[],
  networks: [] as Option[],
  originalLanguage: undefined,
  ratingMax: 10,
  ratingMin: 0,
  sort: 'popularity',
  sortDir: 'desc',
  status: '',
  studios: [] as Option[],
  types: [] as DiscoverTVType[],
  voteCountMax: 1000,
  voteCountMin: 0,
  watchProviders: [] as number[],
} as const;

export const MOVIE_GENRES_MAP = {
  10_402: 'Music',
  10_749: 'Romance',
  10_751: 'Family',
  10_752: 'War',
  10_770: 'TV Movie',
  12: 'Adventure',
  14: 'Fantasy',
  16: 'Animation',
  18: 'Drama',
  27: 'Horror',
  28: 'Action',
  35: 'Comedy',
  36: 'History',
  37: 'Western',
  53: 'Thriller',
  80: 'Crime',
  878: 'Science Fiction',
  9648: 'Mystery',
  99: 'Documentary',
} satisfies Record<number, string>;

export const SERIES_GENRES_MAP = {
  10_751: 'Family',
  10_759: 'Action & Adventure',
  10_762: 'Kids',
  10_763: 'News',
  10_764: 'Reality',
  10_765: 'Sci-Fi & Fantasy',
  10_766: 'Soap',
  10_767: 'Talk',
  10_768: 'War & Politics',
  16: 'Animation',
  18: 'Drama',
  35: 'Comedy',
  37: 'Western',
  80: 'Crime',
  9648: 'Mystery',
  99: 'Documentary',
} satisfies Record<number, string>;

export const LANGUAGES_MAP = {
  aa: 'Afar',
  ab: 'Abkhazian',
  ae: 'Avestan',
  af: 'Afrikaans',
  ak: 'Akan',
  am: 'Amharic',
  an: 'Aragonese',
  ar: 'Arabic',
  as: 'Assamese',
  av: 'Avaric',
  ay: 'Aymara',
  az: 'Azerbaijani',
  ba: 'Bashkir',
  be: 'Belarusian',
  bg: 'Bulgarian',
  bi: 'Bislama',
  bm: 'Bambara',
  bn: 'Bengali',
  bo: 'Tibetan',
  br: 'Breton',
  bs: 'Bosnian',
  ca: 'Catalan',
  ce: 'Chechen',
  ch: 'Chamorro',
  cn: 'Cantonese',
  co: 'Corsican',
  cr: 'Cree',
  cs: 'Czech',
  cu: 'Slavic',
  cv: 'Chuvash',
  cy: 'Welsh',
  da: 'Danish',
  de: 'German',
  dv: 'Divehi',
  dz: 'Dzongkha',
  ee: 'Ewe',
  el: 'Greek',
  en: 'English',
  eo: 'Esperanto',
  es: 'Spanish',
  et: 'Estonian',
  eu: 'Basque',
  fa: 'Persian',
  ff: 'Fulah',
  fi: 'Finnish',
  fj: 'Fijian',
  fo: 'Faroese',
  fr: 'French',
  fy: 'Frisian',
  ga: 'Irish',
  gd: 'Gaelic',
  gl: 'Galician',
  gn: 'Guarani',
  gu: 'Gujarati',
  gv: 'Manx',
  ha: 'Hausa',
  he: 'Hebrew',
  hi: 'Hindi',
  ho: 'Hiri Motu',
  hr: 'Croatian',
  ht: 'Haitian; Haitian Creole',
  hu: 'Hungarian',
  hy: 'Armenian',
  hz: 'Herero',
  ia: 'Interlingua',
  id: 'Indonesian',
  ie: 'Interlingue',
  ig: 'Igbo',
  ii: 'Yi',
  ik: 'Inupiaq',
  io: 'Ido',
  is: 'Icelandic',
  it: 'Italian',
  iu: 'Inuktitut',
  ja: 'Japanese',
  jv: 'Javanese',
  ka: 'Georgian',
  kg: 'Kongo',
  ki: 'Kikuyu',
  kj: 'Kuanyama',
  kk: 'Kazakh',
  kl: 'Kalaallisut',
  km: 'Khmer',
  kn: 'Kannada',
  ko: 'Korean',
  kr: 'Kanuri',
  ks: 'Kashmiri',
  ku: 'Kurdish',
  kv: 'Komi',
  kw: 'Cornish',
  ky: 'Kirghiz',
  la: 'Latin',
  lb: 'Letzeburgesch',
  lg: 'Ganda',
  li: 'Limburgish',
  ln: 'Lingala',
  lo: 'Lao',
  lt: 'Lithuanian',
  lu: 'Luba-Katanga',
  lv: 'Latvian',
  mg: 'Malagasy',
  mh: 'Marshall',
  mi: 'Maori',
  mk: 'Macedonian',
  ml: 'Malayalam',
  mn: 'Mongolian',
  mo: 'Moldavian',
  mr: 'Marathi',
  ms: 'Malay',
  mt: 'Maltese',
  my: 'Burmese',
  na: 'Nauru',
  nb: 'Norwegian Bokmål',
  nd: 'Ndebele',
  ne: 'Nepali',
  ng: 'Ndonga',
  nl: 'Dutch',
  nn: 'Norwegian Nynorsk',
  no: 'Norwegian',
  nr: 'Ndebele',
  nv: 'Navajo',
  ny: 'Chichewa; Nyanja',
  oc: 'Occitan',
  oj: 'Ojibwa',
  om: 'Oromo',
  or: 'Oriya',
  os: 'Ossetian; Ossetic',
  pa: 'Punjabi',
  pi: 'Pali',
  pl: 'Polish',
  ps: 'Pushto',
  pt: 'Portuguese',
  qu: 'Quechua',
  rm: 'Raeto-Romance',
  rn: 'Rundi',
  ro: 'Romanian',
  ru: 'Russian',
  rw: 'Kinyarwanda',
  sa: 'Sanskrit',
  sc: 'Sardinian',
  sd: 'Sindhi',
  se: 'Northern Sami',
  sg: 'Sango',
  sh: 'Serbo-Croatian',
  si: 'Sinhalese',
  sk: 'Slovak',
  sl: 'Slovenian',
  sm: 'Samoan',
  sn: 'Shona',
  so: 'Somali',
  sq: 'Albanian',
  sr: 'Serbian',
  ss: 'Swati',
  st: 'Sotho',
  su: 'Sundanese',
  sv: 'Swedish',
  sw: 'Swahili',
  ta: 'Tamil',
  te: 'Telugu',
  tg: 'Tajik',
  th: 'Thai',
  ti: 'Tigrinya',
  tk: 'Turkmen',
  tl: 'Tagalog',
  tn: 'Tswana',
  to: 'Tonga',
  tr: 'Turkish',
  ts: 'Tsonga',
  tt: 'Tatar',
  tw: 'Twi',
  ty: 'Tahitian',
  ug: 'Uighur',
  uk: 'Ukrainian',
  ur: 'Urdu',
  uz: 'Uzbek',
  ve: 'Venda',
  vi: 'Vietnamese',
  vo: 'Volapük',
  wa: 'Walloon',
  wo: 'Wolof',
  xh: 'Xhosa',
  xx: 'No Language',
  yi: 'Yiddish',
  yo: 'Yoruba',
  za: 'Zhuang',
  zh: 'Mandarin',
  zu: 'Zulu',
} satisfies Record<LanguageISO6391, string>;
