/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TestImport } from './routes/test'
import { Route as SeriesImport } from './routes/series'
import { Route as SearchImport } from './routes/search'
import { Route as IndexImport } from './routes/index'
import { Route as peoplePeopleImport } from './routes/(people)/people'
import { Route as moviesSidebarImport } from './routes/(movies)/_sidebar'
import { Route as moviesMoviespaddedImport } from './routes/(movies)/movies_/_padded'
import { Route as moviesSidebarMoviesImport } from './routes/(movies)/_sidebar/movies'
import { Route as moviesMoviespaddedMovieIdImport } from './routes/(movies)/movies_/_padded/$movieId'
import { Route as moviesMoviespaddedMovieIdSimilarImport } from './routes/(movies)/movies_/_padded/$movieId_/similar'
import { Route as moviesMoviespaddedMovieIdRecommendationsImport } from './routes/(movies)/movies_/_padded/$movieId_/recommendations'
import { Route as moviesMoviespaddedMovieIdCrewImport } from './routes/(movies)/movies_/_padded/$movieId_/crew'
import { Route as moviesMoviespaddedMovieIdCastImport } from './routes/(movies)/movies_/_padded/$movieId_/cast'

// Create Virtual Routes

const moviesImport = createFileRoute('/(movies)')()
const moviesMoviesImport = createFileRoute('/(movies)/movies_')()

// Create/Update Routes

const moviesRoute = moviesImport.update({
  id: '/(movies)',
  getParentRoute: () => rootRoute,
} as any)

const TestRoute = TestImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRoute,
} as any)

const SeriesRoute = SeriesImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => rootRoute,
} as any)

const SearchRoute = SearchImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const moviesMoviesRoute = moviesMoviesImport.update({
  id: '/movies_',
  path: '/movies',
  getParentRoute: () => moviesRoute,
} as any)

const peoplePeopleRoute = peoplePeopleImport.update({
  id: '/(people)/people',
  path: '/people',
  getParentRoute: () => rootRoute,
} as any)

const moviesSidebarRoute = moviesSidebarImport.update({
  id: '/_sidebar',
  getParentRoute: () => moviesRoute,
} as any)

const moviesMoviespaddedRoute = moviesMoviespaddedImport.update({
  id: '/_padded',
  getParentRoute: () => moviesMoviesRoute,
} as any)

const moviesSidebarMoviesRoute = moviesSidebarMoviesImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => moviesSidebarRoute,
} as any)

const moviesMoviespaddedMovieIdRoute = moviesMoviespaddedMovieIdImport.update({
  id: '/$movieId',
  path: '/$movieId',
  getParentRoute: () => moviesMoviespaddedRoute,
} as any)

const moviesMoviespaddedMovieIdSimilarRoute =
  moviesMoviespaddedMovieIdSimilarImport.update({
    id: '/$movieId_/similar',
    path: '/$movieId/similar',
    getParentRoute: () => moviesMoviespaddedRoute,
  } as any)

const moviesMoviespaddedMovieIdRecommendationsRoute =
  moviesMoviespaddedMovieIdRecommendationsImport.update({
    id: '/$movieId_/recommendations',
    path: '/$movieId/recommendations',
    getParentRoute: () => moviesMoviespaddedRoute,
  } as any)

const moviesMoviespaddedMovieIdCrewRoute =
  moviesMoviespaddedMovieIdCrewImport.update({
    id: '/$movieId_/crew',
    path: '/$movieId/crew',
    getParentRoute: () => moviesMoviespaddedRoute,
  } as any)

const moviesMoviespaddedMovieIdCastRoute =
  moviesMoviespaddedMovieIdCastImport.update({
    id: '/$movieId_/cast',
    path: '/$movieId/cast',
    getParentRoute: () => moviesMoviespaddedRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchImport
      parentRoute: typeof rootRoute
    }
    '/series': {
      id: '/series'
      path: '/series'
      fullPath: '/series'
      preLoaderRoute: typeof SeriesImport
      parentRoute: typeof rootRoute
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestImport
      parentRoute: typeof rootRoute
    }
    '/(movies)': {
      id: '/(movies)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof moviesImport
      parentRoute: typeof rootRoute
    }
    '/(movies)/_sidebar': {
      id: '/(movies)/_sidebar'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof moviesSidebarImport
      parentRoute: typeof moviesRoute
    }
    '/(people)/people': {
      id: '/(people)/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof peoplePeopleImport
      parentRoute: typeof rootRoute
    }
    '/(movies)/_sidebar/movies': {
      id: '/(movies)/_sidebar/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof moviesSidebarMoviesImport
      parentRoute: typeof moviesSidebarImport
    }
    '/(movies)/movies_': {
      id: '/(movies)/movies_'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof moviesMoviesImport
      parentRoute: typeof moviesImport
    }
    '/(movies)/movies_/_padded': {
      id: '/(movies)/movies_/_padded'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof moviesMoviespaddedImport
      parentRoute: typeof moviesMoviesRoute
    }
    '/(movies)/movies_/_padded/$movieId': {
      id: '/(movies)/movies_/_padded/$movieId'
      path: '/$movieId'
      fullPath: '/movies/$movieId'
      preLoaderRoute: typeof moviesMoviespaddedMovieIdImport
      parentRoute: typeof moviesMoviespaddedImport
    }
    '/(movies)/movies_/_padded/$movieId_/cast': {
      id: '/(movies)/movies_/_padded/$movieId_/cast'
      path: '/$movieId/cast'
      fullPath: '/movies/$movieId/cast'
      preLoaderRoute: typeof moviesMoviespaddedMovieIdCastImport
      parentRoute: typeof moviesMoviespaddedImport
    }
    '/(movies)/movies_/_padded/$movieId_/crew': {
      id: '/(movies)/movies_/_padded/$movieId_/crew'
      path: '/$movieId/crew'
      fullPath: '/movies/$movieId/crew'
      preLoaderRoute: typeof moviesMoviespaddedMovieIdCrewImport
      parentRoute: typeof moviesMoviespaddedImport
    }
    '/(movies)/movies_/_padded/$movieId_/recommendations': {
      id: '/(movies)/movies_/_padded/$movieId_/recommendations'
      path: '/$movieId/recommendations'
      fullPath: '/movies/$movieId/recommendations'
      preLoaderRoute: typeof moviesMoviespaddedMovieIdRecommendationsImport
      parentRoute: typeof moviesMoviespaddedImport
    }
    '/(movies)/movies_/_padded/$movieId_/similar': {
      id: '/(movies)/movies_/_padded/$movieId_/similar'
      path: '/$movieId/similar'
      fullPath: '/movies/$movieId/similar'
      preLoaderRoute: typeof moviesMoviespaddedMovieIdSimilarImport
      parentRoute: typeof moviesMoviespaddedImport
    }
  }
}

// Create and export the route tree

interface moviesSidebarRouteChildren {
  moviesSidebarMoviesRoute: typeof moviesSidebarMoviesRoute
}

const moviesSidebarRouteChildren: moviesSidebarRouteChildren = {
  moviesSidebarMoviesRoute: moviesSidebarMoviesRoute,
}

const moviesSidebarRouteWithChildren = moviesSidebarRoute._addFileChildren(
  moviesSidebarRouteChildren,
)

interface moviesMoviespaddedRouteChildren {
  moviesMoviespaddedMovieIdRoute: typeof moviesMoviespaddedMovieIdRoute
  moviesMoviespaddedMovieIdCastRoute: typeof moviesMoviespaddedMovieIdCastRoute
  moviesMoviespaddedMovieIdCrewRoute: typeof moviesMoviespaddedMovieIdCrewRoute
  moviesMoviespaddedMovieIdRecommendationsRoute: typeof moviesMoviespaddedMovieIdRecommendationsRoute
  moviesMoviespaddedMovieIdSimilarRoute: typeof moviesMoviespaddedMovieIdSimilarRoute
}

const moviesMoviespaddedRouteChildren: moviesMoviespaddedRouteChildren = {
  moviesMoviespaddedMovieIdRoute: moviesMoviespaddedMovieIdRoute,
  moviesMoviespaddedMovieIdCastRoute: moviesMoviespaddedMovieIdCastRoute,
  moviesMoviespaddedMovieIdCrewRoute: moviesMoviespaddedMovieIdCrewRoute,
  moviesMoviespaddedMovieIdRecommendationsRoute:
    moviesMoviespaddedMovieIdRecommendationsRoute,
  moviesMoviespaddedMovieIdSimilarRoute: moviesMoviespaddedMovieIdSimilarRoute,
}

const moviesMoviespaddedRouteWithChildren =
  moviesMoviespaddedRoute._addFileChildren(moviesMoviespaddedRouteChildren)

interface moviesMoviesRouteChildren {
  moviesMoviespaddedRoute: typeof moviesMoviespaddedRouteWithChildren
}

const moviesMoviesRouteChildren: moviesMoviesRouteChildren = {
  moviesMoviespaddedRoute: moviesMoviespaddedRouteWithChildren,
}

const moviesMoviesRouteWithChildren = moviesMoviesRoute._addFileChildren(
  moviesMoviesRouteChildren,
)

interface moviesRouteChildren {
  moviesSidebarRoute: typeof moviesSidebarRouteWithChildren
  moviesMoviesRoute: typeof moviesMoviesRouteWithChildren
}

const moviesRouteChildren: moviesRouteChildren = {
  moviesSidebarRoute: moviesSidebarRouteWithChildren,
  moviesMoviesRoute: moviesMoviesRouteWithChildren,
}

const moviesRouteWithChildren =
  moviesRoute._addFileChildren(moviesRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof moviesSidebarRouteWithChildren
  '/search': typeof SearchRoute
  '/series': typeof SeriesRoute
  '/test': typeof TestRoute
  '/people': typeof peoplePeopleRoute
  '/movies': typeof moviesMoviespaddedRouteWithChildren
  '/movies/$movieId': typeof moviesMoviespaddedMovieIdRoute
  '/movies/$movieId/cast': typeof moviesMoviespaddedMovieIdCastRoute
  '/movies/$movieId/crew': typeof moviesMoviespaddedMovieIdCrewRoute
  '/movies/$movieId/recommendations': typeof moviesMoviespaddedMovieIdRecommendationsRoute
  '/movies/$movieId/similar': typeof moviesMoviespaddedMovieIdSimilarRoute
}

export interface FileRoutesByTo {
  '/': typeof moviesSidebarRouteWithChildren
  '/search': typeof SearchRoute
  '/series': typeof SeriesRoute
  '/test': typeof TestRoute
  '/people': typeof peoplePeopleRoute
  '/movies': typeof moviesMoviespaddedRouteWithChildren
  '/movies/$movieId': typeof moviesMoviespaddedMovieIdRoute
  '/movies/$movieId/cast': typeof moviesMoviespaddedMovieIdCastRoute
  '/movies/$movieId/crew': typeof moviesMoviespaddedMovieIdCrewRoute
  '/movies/$movieId/recommendations': typeof moviesMoviespaddedMovieIdRecommendationsRoute
  '/movies/$movieId/similar': typeof moviesMoviespaddedMovieIdSimilarRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/series': typeof SeriesRoute
  '/test': typeof TestRoute
  '/(movies)': typeof moviesRouteWithChildren
  '/(movies)/_sidebar': typeof moviesSidebarRouteWithChildren
  '/(people)/people': typeof peoplePeopleRoute
  '/(movies)/_sidebar/movies': typeof moviesSidebarMoviesRoute
  '/(movies)/movies_': typeof moviesMoviesRouteWithChildren
  '/(movies)/movies_/_padded': typeof moviesMoviespaddedRouteWithChildren
  '/(movies)/movies_/_padded/$movieId': typeof moviesMoviespaddedMovieIdRoute
  '/(movies)/movies_/_padded/$movieId_/cast': typeof moviesMoviespaddedMovieIdCastRoute
  '/(movies)/movies_/_padded/$movieId_/crew': typeof moviesMoviespaddedMovieIdCrewRoute
  '/(movies)/movies_/_padded/$movieId_/recommendations': typeof moviesMoviespaddedMovieIdRecommendationsRoute
  '/(movies)/movies_/_padded/$movieId_/similar': typeof moviesMoviespaddedMovieIdSimilarRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/search'
    | '/series'
    | '/test'
    | '/people'
    | '/movies'
    | '/movies/$movieId'
    | '/movies/$movieId/cast'
    | '/movies/$movieId/crew'
    | '/movies/$movieId/recommendations'
    | '/movies/$movieId/similar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/search'
    | '/series'
    | '/test'
    | '/people'
    | '/movies'
    | '/movies/$movieId'
    | '/movies/$movieId/cast'
    | '/movies/$movieId/crew'
    | '/movies/$movieId/recommendations'
    | '/movies/$movieId/similar'
  id:
    | '__root__'
    | '/'
    | '/search'
    | '/series'
    | '/test'
    | '/(movies)'
    | '/(movies)/_sidebar'
    | '/(people)/people'
    | '/(movies)/_sidebar/movies'
    | '/(movies)/movies_'
    | '/(movies)/movies_/_padded'
    | '/(movies)/movies_/_padded/$movieId'
    | '/(movies)/movies_/_padded/$movieId_/cast'
    | '/(movies)/movies_/_padded/$movieId_/crew'
    | '/(movies)/movies_/_padded/$movieId_/recommendations'
    | '/(movies)/movies_/_padded/$movieId_/similar'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SearchRoute: typeof SearchRoute
  SeriesRoute: typeof SeriesRoute
  TestRoute: typeof TestRoute
  moviesRoute: typeof moviesRouteWithChildren
  peoplePeopleRoute: typeof peoplePeopleRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SearchRoute: SearchRoute,
  SeriesRoute: SeriesRoute,
  TestRoute: TestRoute,
  moviesRoute: moviesRouteWithChildren,
  peoplePeopleRoute: peoplePeopleRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/search",
        "/series",
        "/test",
        "/(movies)",
        "/(people)/people"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/search": {
      "filePath": "search.tsx"
    },
    "/series": {
      "filePath": "series.tsx"
    },
    "/test": {
      "filePath": "test.tsx"
    },
    "/(movies)": {
      "filePath": "(movies)",
      "children": [
        "/(movies)/_sidebar",
        "/(movies)/movies_"
      ]
    },
    "/(movies)/_sidebar": {
      "filePath": "(movies)/_sidebar.tsx",
      "parent": "/(movies)",
      "children": [
        "/(movies)/_sidebar/movies"
      ]
    },
    "/(people)/people": {
      "filePath": "(people)/people.tsx"
    },
    "/(movies)/_sidebar/movies": {
      "filePath": "(movies)/_sidebar/movies.tsx",
      "parent": "/(movies)/_sidebar"
    },
    "/(movies)/movies_": {
      "filePath": "(movies)/movies_",
      "parent": "/(movies)",
      "children": [
        "/(movies)/movies_/_padded"
      ]
    },
    "/(movies)/movies_/_padded": {
      "filePath": "(movies)/movies_/_padded.tsx",
      "parent": "/(movies)/movies_",
      "children": [
        "/(movies)/movies_/_padded/$movieId",
        "/(movies)/movies_/_padded/$movieId_/cast",
        "/(movies)/movies_/_padded/$movieId_/crew",
        "/(movies)/movies_/_padded/$movieId_/recommendations",
        "/(movies)/movies_/_padded/$movieId_/similar"
      ]
    },
    "/(movies)/movies_/_padded/$movieId": {
      "filePath": "(movies)/movies_/_padded/$movieId.tsx",
      "parent": "/(movies)/movies_/_padded"
    },
    "/(movies)/movies_/_padded/$movieId_/cast": {
      "filePath": "(movies)/movies_/_padded/$movieId_/cast.tsx",
      "parent": "/(movies)/movies_/_padded"
    },
    "/(movies)/movies_/_padded/$movieId_/crew": {
      "filePath": "(movies)/movies_/_padded/$movieId_/crew.tsx",
      "parent": "/(movies)/movies_/_padded"
    },
    "/(movies)/movies_/_padded/$movieId_/recommendations": {
      "filePath": "(movies)/movies_/_padded/$movieId_/recommendations.tsx",
      "parent": "/(movies)/movies_/_padded"
    },
    "/(movies)/movies_/_padded/$movieId_/similar": {
      "filePath": "(movies)/movies_/_padded/$movieId_/similar.tsx",
      "parent": "/(movies)/movies_/_padded"
    }
  }
}
ROUTE_MANIFEST_END */
