/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TvImport } from './routes/tv'
import { Route as TestImport } from './routes/test'
import { Route as IndexImport } from './routes/index'
import { Route as moviesLayoutImport } from './routes/(movies)/_layout'
import { Route as moviesMoviesMovieIdImport } from './routes/(movies)/movies_/$movieId'
import { Route as moviesLayoutMoviesImport } from './routes/(movies)/_layout/movies'
import { Route as moviesMoviesMovieIdCastImport } from './routes/(movies)/movies_/$movieId_/cast'

// Create Virtual Routes

const moviesImport = createFileRoute('/(movies)')()

// Create/Update Routes

const moviesRoute = moviesImport.update({
  id: '/(movies)',
  getParentRoute: () => rootRoute,
} as any)

const TvRoute = TvImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => rootRoute,
} as any)

const TestRoute = TestImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const moviesLayoutRoute = moviesLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => moviesRoute,
} as any)

const moviesMoviesMovieIdRoute = moviesMoviesMovieIdImport.update({
  id: '/movies_/$movieId',
  path: '/movies/$movieId',
  getParentRoute: () => moviesRoute,
} as any)

const moviesLayoutMoviesRoute = moviesLayoutMoviesImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => moviesLayoutRoute,
} as any)

const moviesMoviesMovieIdCastRoute = moviesMoviesMovieIdCastImport.update({
  id: '/movies_/$movieId_/cast',
  path: '/movies/$movieId/cast',
  getParentRoute: () => moviesRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestImport
      parentRoute: typeof rootRoute
    }
    '/tv': {
      id: '/tv'
      path: '/tv'
      fullPath: '/tv'
      preLoaderRoute: typeof TvImport
      parentRoute: typeof rootRoute
    }
    '/(movies)': {
      id: '/(movies)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof moviesImport
      parentRoute: typeof rootRoute
    }
    '/(movies)/_layout': {
      id: '/(movies)/_layout'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof moviesLayoutImport
      parentRoute: typeof moviesRoute
    }
    '/(movies)/_layout/movies': {
      id: '/(movies)/_layout/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof moviesLayoutMoviesImport
      parentRoute: typeof moviesLayoutImport
    }
    '/(movies)/movies_/$movieId': {
      id: '/(movies)/movies_/$movieId'
      path: '/movies/$movieId'
      fullPath: '/movies/$movieId'
      preLoaderRoute: typeof moviesMoviesMovieIdImport
      parentRoute: typeof moviesImport
    }
    '/(movies)/movies_/$movieId_/cast': {
      id: '/(movies)/movies_/$movieId_/cast'
      path: '/movies/$movieId/cast'
      fullPath: '/movies/$movieId/cast'
      preLoaderRoute: typeof moviesMoviesMovieIdCastImport
      parentRoute: typeof moviesImport
    }
  }
}

// Create and export the route tree

interface moviesLayoutRouteChildren {
  moviesLayoutMoviesRoute: typeof moviesLayoutMoviesRoute
}

const moviesLayoutRouteChildren: moviesLayoutRouteChildren = {
  moviesLayoutMoviesRoute: moviesLayoutMoviesRoute,
}

const moviesLayoutRouteWithChildren = moviesLayoutRoute._addFileChildren(
  moviesLayoutRouteChildren,
)

interface moviesRouteChildren {
  moviesLayoutRoute: typeof moviesLayoutRouteWithChildren
  moviesMoviesMovieIdRoute: typeof moviesMoviesMovieIdRoute
  moviesMoviesMovieIdCastRoute: typeof moviesMoviesMovieIdCastRoute
}

const moviesRouteChildren: moviesRouteChildren = {
  moviesLayoutRoute: moviesLayoutRouteWithChildren,
  moviesMoviesMovieIdRoute: moviesMoviesMovieIdRoute,
  moviesMoviesMovieIdCastRoute: moviesMoviesMovieIdCastRoute,
}

const moviesRouteWithChildren =
  moviesRoute._addFileChildren(moviesRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof moviesLayoutRouteWithChildren
  '/test': typeof TestRoute
  '/tv': typeof TvRoute
  '/movies': typeof moviesLayoutMoviesRoute
  '/movies/$movieId': typeof moviesMoviesMovieIdRoute
  '/movies/$movieId/cast': typeof moviesMoviesMovieIdCastRoute
}

export interface FileRoutesByTo {
  '/': typeof moviesLayoutRouteWithChildren
  '/test': typeof TestRoute
  '/tv': typeof TvRoute
  '/movies': typeof moviesLayoutMoviesRoute
  '/movies/$movieId': typeof moviesMoviesMovieIdRoute
  '/movies/$movieId/cast': typeof moviesMoviesMovieIdCastRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/test': typeof TestRoute
  '/tv': typeof TvRoute
  '/(movies)': typeof moviesRouteWithChildren
  '/(movies)/_layout': typeof moviesLayoutRouteWithChildren
  '/(movies)/_layout/movies': typeof moviesLayoutMoviesRoute
  '/(movies)/movies_/$movieId': typeof moviesMoviesMovieIdRoute
  '/(movies)/movies_/$movieId_/cast': typeof moviesMoviesMovieIdCastRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/test'
    | '/tv'
    | '/movies'
    | '/movies/$movieId'
    | '/movies/$movieId/cast'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/test'
    | '/tv'
    | '/movies'
    | '/movies/$movieId'
    | '/movies/$movieId/cast'
  id:
    | '__root__'
    | '/'
    | '/test'
    | '/tv'
    | '/(movies)'
    | '/(movies)/_layout'
    | '/(movies)/_layout/movies'
    | '/(movies)/movies_/$movieId'
    | '/(movies)/movies_/$movieId_/cast'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TestRoute: typeof TestRoute
  TvRoute: typeof TvRoute
  moviesRoute: typeof moviesRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TestRoute: TestRoute,
  TvRoute: TvRoute,
  moviesRoute: moviesRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/test",
        "/tv",
        "/(movies)"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/test": {
      "filePath": "test.tsx"
    },
    "/tv": {
      "filePath": "tv.tsx"
    },
    "/(movies)": {
      "filePath": "(movies)",
      "children": [
        "/(movies)/_layout",
        "/(movies)/movies_/$movieId",
        "/(movies)/movies_/$movieId_/cast"
      ]
    },
    "/(movies)/_layout": {
      "filePath": "(movies)/_layout.tsx",
      "parent": "/(movies)",
      "children": [
        "/(movies)/_layout/movies"
      ]
    },
    "/(movies)/_layout/movies": {
      "filePath": "(movies)/_layout/movies.tsx",
      "parent": "/(movies)/_layout"
    },
    "/(movies)/movies_/$movieId": {
      "filePath": "(movies)/movies_/$movieId.tsx",
      "parent": "/(movies)"
    },
    "/(movies)/movies_/$movieId_/cast": {
      "filePath": "(movies)/movies_/$movieId_/cast.tsx",
      "parent": "/(movies)"
    }
  }
}
ROUTE_MANIFEST_END */
